### ISSUE TITLE
Project subject brainstorming & discussion

### ISSUE THREAD

**Issue by jaepang** [rbals0445/2021fall_41class_team9#1]
Please write down any idea of main project.

**Comment by rbals0445** [comment]
### 주제 : 모든 동아리가 사용할 수 있는 동아리실 제공

- 제안 이유 :  편리함이나 긍정적 효과를 가져올 수 있는 Smart campus와 관련된 주제 && 다른 project와의 Integration 가능성을 고려하여 개발 항목에도 부합.

- 개요 : 코로나로 인한 오프라인 활동의 제약이 있는만큼, SKKU 학생들이 이용할 수 있는 공통적인 방을 만들어 제공합니다.
- 세부사항 : 
  - 공통 모듈 : 교실, 회의실
  - 커스터마이징 가능한 모듈(가능하다면) : 미술동아리에게는 캔버스가 필요할 것이고, 음악 동아리에게는 드럼과 같은 악기가 필요합니다.  (맵을 유동으로 바꿀수는 없는것 같고, 물품들을 미리 놓고, 각자가 필요한 물품을 가져다 놓고 쓰는방식을 생각중입니다)

- 확장성 :  나중에 생길 MOOC같은 것을 위한 교실로도 사용이 가능 할 것이고, 커스터마이징이 가능하다면 각종 행사에 맞춰 바꿔 사용할 수 있습니다.


- 참고한 링크 : [여기](https://www.youtube.com/watch?v=HO-P2OqO1ac)
